name: 'Apply tag action'
description: 'Adds a tag to the repo if the tag does not exist.'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github secret key'
    required: true
  tag:
    description: 'The tag to be applied'
    required: true
  outputs:
    tagcreated:
      description: A "yes" or "no", indicating a new tag was created.
runs:
  using: 'node16'
  main: 'index.js'
